"""
报告生成器.

负责生成 POC 验证报告,支持 HTML、JSON、PDF 等多种格式。
"""
import json
import logging
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Union

from backend.ai_agents.poc_system.utils import calculate_severity_distribution
from backend.models import POCVerificationResult, POCVerificationTask


logger = logging.getLogger(__name__)


class Language(Enum):
    ZH_CN = "zh_CN"
    EN_US = "en_US"
    JA_JP = "ja_JP"


@dataclass
class ReportSection:
    section_id: str
    title: str
    content: str = ""
    enabled: bool = True
    order: int = 0


@dataclass
class TemplateVariable:
    name: str
    value: Any
    description: str = ""


@dataclass
class CustomTemplate:
    name: str
    base_template: Optional[str] = None
    html_template: str = ""
    variables: Dict[str, TemplateVariable] = field(default_factory=dict)
    sections: Dict[str, ReportSection] = field(default_factory=dict)


class I18N:
    """多语言支持类"""
    
    TRANSLATIONS: Dict[Language, Dict[str, str]] = {
        Language.ZH_CN: {
            "report_title": "POC 验证报告",
            "generated_time": "生成时间",
            "executive_summary": "执行摘要",
            "total_results": "总结果数",
            "vulnerabilities_found": "发现漏洞",
            "no_vulnerabilities": "未发现漏洞",
            "vulnerability_rate": "漏洞率",
            "verification_details": "验证结果详情",
            "target": "目标",
            "confidence": "置信度",
            "severity": "严重度",
            "critical": "严重",
            "high": "高危",
            "medium": "中危",
            "low": "低危",
            "info": "信息",
            "result": "结果",
            "footer_text": "报告由 WebScan AI 安全平台生成",
            "table_of_contents": "目录",
            "severity_distribution": "严重度分布",
            "vulnerability_timeline": "漏洞时间线",
            "target_risk_heatmap": "目标风险热力图",
            "statistics": "统计信息",
            "recommendations": "修复建议",
            "vulnerable": "存在漏洞",
            "not_vulnerable": "无漏洞",
            "cvss_score": "CVSS 评分",
            "execution_time": "执行时间",
            "poc_name": "POC 名称",
            "overview": "概览",
            "risk_assessment": "风险评估",
            "affected_targets": "受影响目标",
            "no_vulnerabilities_found": "未发现任何漏洞",
            "vulnerabilities_detected": "检测到漏洞",
            "executive_summary_text": "本次安全测试共扫描了 {total} 个目标，发现 {vuln} 个漏洞，漏洞率为 {rate}%。其中严重级别 {critical} 个，高危 {high} 个，中危 {medium} 个，低危 {low} 个。"
        },
        Language.EN_US: {
            "report_title": "POC Verification Report",
            "generated_time": "Generated Time",
            "executive_summary": "Executive Summary",
            "total_results": "Total Results",
            "vulnerabilities_found": "Vulnerabilities Found",
            "no_vulnerabilities": "No Vulnerabilities",
            "vulnerability_rate": "Vulnerability Rate",
            "verification_details": "Verification Details",
            "target": "Target",
            "confidence": "Confidence",
            "severity": "Severity",
            "critical": "Critical",
            "high": "High",
            "medium": "Medium",
            "low": "Low",
            "info": "Info",
            "result": "Result",
            "footer_text": "Report generated by WebScan AI Security Platform",
            "table_of_contents": "Table of Contents",
            "severity_distribution": "Severity Distribution",
            "vulnerability_timeline": "Vulnerability Timeline",
            "target_risk_heatmap": "Target Risk Heatmap",
            "statistics": "Statistics",
            "recommendations": "Recommendations",
            "vulnerable": "Vulnerable",
            "not_vulnerable": "Not Vulnerable",
            "cvss_score": "CVSS Score",
            "execution_time": "Execution Time",
            "poc_name": "POC Name",
            "overview": "Overview",
            "risk_assessment": "Risk Assessment",
            "affected_targets": "Affected Targets",
            "no_vulnerabilities_found": "No vulnerabilities found",
            "vulnerabilities_detected": "Vulnerabilities Detected",
            "executive_summary_text": "This security test scanned {total} targets and found {vuln} vulnerabilities with a vulnerability rate of {rate}%. Among them, {critical} critical, {high} high, {medium} medium, and {low} low severity."
        },
        Language.JA_JP: {
            "report_title": "POC検証レポート",
            "generated_time": "生成時間",
            "executive_summary": "エグゼクティブサマリー",
            "total_results": "総結果数",
            "vulnerabilities_found": "脆弱性発見数",
            "no_vulnerabilities": "脆弱性なし",
            "vulnerability_rate": "脆弱性率",
            "verification_details": "検証結果詳細",
            "target": "ターゲット",
            "confidence": "信頼度",
            "severity": "重大度",
            "critical": "重大",
            "high": "高",
            "medium": "中",
            "low": "低",
            "info": "情報",
            "result": "結果",
            "footer_text": "WebScan AIセキュリティプラットフォームで生成されたレポート",
            "table_of_contents": "目次",
            "severity_distribution": "重大度分布",
            "vulnerability_timeline": "脆弱性タイムライン",
            "target_risk_heatmap": "ターゲットリスクヒートマップ",
            "statistics": "統計情報",
            "recommendations": "推奨事項",
            "vulnerable": "脆弱性あり",
            "not_vulnerable": "脆弱性なし",
            "cvss_score": "CVSSスコア",
            "execution_time": "実行時間",
            "poc_name": "POC名",
            "overview": "概要",
            "risk_assessment": "リスク評価",
            "affected_targets": "影響を受けるターゲット",
            "no_vulnerabilities_found": "脆弱性は見つかりませんでした",
            "vulnerabilities_detected": "脆弱性が検出されました",
            "executive_summary_text": "このセキュリティテストでは{total}個のターゲットをスキャンし、{vuln}個の脆弱性を発見しました。脆弱性率は{rate}%です。うち重大{critical}個、高{high}個、中{medium}個、低{low}個です。"
        }
    }
    
    def __init__(self, language: Language = Language.ZH_CN):
        self.language = language
    
    def get(self, key: str, **kwargs) -> str:
        text = self.TRANSLATIONS.get(self.language, self.TRANSLATIONS[Language.ZH_CN]).get(key, key)
        if kwargs:
            return text.format(**kwargs)
        return text
    
    def set_language(self, language: Language) -> None:
        self.language = language


class ReportGenerator:
    """
    报告生成器类.

    负责生成 POC 验证报告,包括:
    - HTML 格式报告(带图表)
    - JSON 格式报告(结构化数据)
    - PDF 格式报告(可打印)
    - 执行摘要生成
    - 漏洞详情列表
    - 统计信息
    - 自定义模板支持
    - 多语言支持

    Attributes:
        report_templates: 报告模板字典.
        custom_templates: 自定义模板字典.
        enabled_sections: 启用的报告章节集合.
        i18n: 多语言支持实例.
    """

    def __init__(self):
        self.report_templates: Dict[str, Callable] = {
            "html": self._generate_html_report,
            "json": self._generate_json_report,
            "pdf": self._generate_pdf_report
        }
        self.custom_templates: Dict[str, CustomTemplate] = {}
        self.enabled_sections: Set[str] = {
            "executive_summary",
            "severity_distribution_chart",
            "vulnerability_timeline_chart",
            "target_risk_heatmap",
            "verification_details",
            "statistics",
            "recommendations"
        }
        self.i18n = I18N()
        
        logger.info("✅ 报告生成器初始化完成")
    
    def register_custom_template(self, template: CustomTemplate) -> None:
        """
        注册自定义模板
        
        Args:
            template: 自定义模板对象
        """
        if template.base_template and template.base_template in self.custom_templates:
            base = self.custom_templates[template.base_template]
            merged_vars = deepcopy(base.variables)
            merged_vars.update(template.variables)
            template.variables = merged_vars
            
            merged_sections = deepcopy(base.sections)
            merged_sections.update(template.sections)
            template.sections = merged_sections
            
            if not template.html_template:
                template.html_template = base.html_template
        
        self.custom_templates[template.name] = template
        logger.info(f"✅ 已注册自定义模板: {template.name}")
    
    def unregister_custom_template(self, template_name: str) -> bool:
        """
        注销自定义模板
        
        Args:
            template_name: 模板名称
            
        Returns:
            bool: 是否成功注销
        """
        if template_name in self.custom_templates:
            del self.custom_templates[template_name]
            logger.info(f"✅ 已注销自定义模板: {template_name}")
            return True
        return False
    
    def get_template_variables(self, template_name: str) -> Dict[str, Any]:
        """
        获取模板变量
        
        Args:
            template_name: 模板名称
            
        Returns:
            Dict: 模板变量字典
        """
        if template_name in self.custom_templates:
            return {k: v.value for k, v in self.custom_templates[template_name].variables.items()}
        return {}
    
    def set_template_variable(self, template_name: str, var_name: str, value: Any) -> bool:
        """
        设置模板变量
        
        Args:
            template_name: 模板名称
            var_name: 变量名
            value: 变量值
            
        Returns:
            bool: 是否成功设置
        """
        if template_name in self.custom_templates:
            if var_name in self.custom_templates[template_name].variables:
                self.custom_templates[template_name].variables[var_name].value = value
                return True
            else:
                self.custom_templates[template_name].variables[var_name] = TemplateVariable(
                    name=var_name,
                    value=value
                )
                return True
        return False
    
    def enable_section(self, section_id: str) -> None:
        """启用报告章节"""
        self.enabled_sections.add(section_id)
    
    def disable_section(self, section_id: str) -> None:
        """禁用报告章节"""
        self.enabled_sections.discard(section_id)
    
    def is_section_enabled(self, section_id: str) -> bool:
        """检查章节是否启用"""
        return section_id in self.enabled_sections
    
    def set_language(self, language: Language) -> None:
        """设置报告语言"""
        self.i18n.set_language(language)
    
    async def generate_report(
        self,
        verification_task: POCVerificationTask,
        format: str = "html",
        output_path: Optional[str] = None,
        template_name: Optional[str] = None,
        workflow_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        生成 POC 验证报告
        
        Args:
            verification_task: POC 验证任务对象
            format: 报告格式(html, json, pdf)
            output_path: 输出文件路径,None 则返回内容
            template_name: 自定义模板名称
            workflow_data: 工作流数据（包含执行历史、任务规划等）
            
        Returns:
            str: 报告内容或文件路径
        """
        logger.info(f"📄 开始生成报告,格式: {format}, 任务: {verification_task.poc_name}")
        
        results = await POCVerificationResult.filter(
            verification_task=verification_task.id
        ).order_by("-created_at")
        
        if format not in self.report_templates:
            raise ValueError(f"不支持的报告格式: {format}")
        
        custom_template = None
        if template_name and template_name in self.custom_templates:
            custom_template = self.custom_templates[template_name]
        
        report_content = await self.report_templates[format](
            verification_task,
            results,
            custom_template=custom_template,
            workflow_data=workflow_data
        )
        
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            mode = 'wb' if format == 'pdf' and isinstance(report_content, bytes) else 'w'
            encoding = None if mode == 'wb' else 'utf-8'
            with open(output_path, mode, encoding=encoding) as f:
                f.write(report_content)
            logger.info(f"✅ 报告已保存: {output_path}")
            return output_path
        else:
            return report_content
    
    async def generate_batch_report(
        self,
        verification_tasks: List[POCVerificationTask],
        format: str = "html",
        output_path: Optional[str] = None,
        template_name: Optional[str] = None
    ) -> str:
        """
        生成批量 POC 验证报告
        
        Args:
            verification_tasks: POC 验证任务列表
            format: 报告格式(html, json, pdf)
            output_path: 输出文件路径,None 则返回内容
            template_name: 自定义模板名称
            
        Returns:
            str: 报告内容或文件路径
        """
        logger.info(f"📄 开始生成批量报告,格式: {format}, 任务数: {len(verification_tasks)}")
        
        all_results = []
        for task in verification_tasks:
            results = await POCVerificationResult.filter(
                verification_task=task.id
            ).order_by("-created_at")
            all_results.extend(results)
        
        if format not in self.report_templates:
            raise ValueError(f"不支持的报告格式: {format}")
        
        custom_template = None
        if template_name and template_name in self.custom_templates:
            custom_template = self.custom_templates[template_name]
        
        report_content = await self.report_templates[format](
            verification_tasks,
            all_results,
            is_batch=True,
            custom_template=custom_template
        )
        
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            mode = 'wb' if format == 'pdf' and isinstance(report_content, bytes) else 'w'
            encoding = None if mode == 'wb' else 'utf-8'
            with open(output_path, mode, encoding=encoding) as f:
                f.write(report_content)
            logger.info(f"✅ 批量报告已保存: {output_path}")
            return output_path
        else:
            return report_content
    
    async def merge_reports(
        self,
        reports: List[Dict[str, Any]],
        format: str = "html",
        output_path: Optional[str] = None
    ) -> str:
        """
        合并多个报告
        
        Args:
            reports: 报告数据列表
            format: 输出格式
            output_path: 输出文件路径
            
        Returns:
            str: 合并后的报告内容或文件路径
        """
        logger.info(f"📄 开始合并 {len(reports)} 个报告")
        
        merged_results = []
        for report in reports:
            if "results" in report:
                merged_results.extend(report["results"])
        
        merged_data = {
            "report_type": "merged",
            "generated_at": datetime.now().isoformat(),
            "source_reports": len(reports),
            "summary": self._calculate_merged_summary(reports),
            "results": merged_results
        }
        
        if format == "json":
            content = json.dumps(merged_data, ensure_ascii=False, indent=2)
        else:
            content = await self._generate_merged_html_report(merged_data)
        
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            logger.info(f"✅ 合并报告已保存: {output_path}")
            return output_path
        
        return content
    
    def _calculate_merged_summary(self, reports: List[Dict[str, Any]]) -> Dict[str, Any]:
        """计算合并报告的摘要"""
        total_results = 0
        vulnerable_count = 0
        severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        
        for report in reports:
            summary = report.get("summary", {})
            total_results += summary.get("total_results", 0)
            vulnerable_count += summary.get("vulnerable_count", 0)
            
            severity_dist = summary.get("severity_distribution", {})
            for sev in severity_counts:
                severity_counts[sev] += severity_dist.get(sev, 0)
        
        return {
            "total_results": total_results,
            "vulnerable_count": vulnerable_count,
            "not_vulnerable_count": total_results - vulnerable_count,
            "vulnerability_rate": (vulnerable_count / total_results * 100) if total_results > 0 else 0,
            "severity_distribution": severity_counts
        }
    
    async def _generate_merged_html_report(self, merged_data: Dict[str, Any]) -> str:
        """生成合并报告的 HTML"""
        summary = merged_data["summary"]
        
        return f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>合并报告</title>
    {self._get_modern_css()}
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>合并安全报告</h1>
            <p>生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>合并来源: {merged_data['source_reports']} 个报告</p>
        </div>
        
        <div class="summary">
            <h2>总体摘要</h2>
            <div class="stats">
                <div class="stat-card">
                    <h3>总扫描结果</h3>
                    <div class="value">{summary['total_results']}</div>
                </div>
                <div class="stat-card">
                    <h3>发现漏洞</h3>
                    <div class="value danger">{summary['vulnerable_count']}</div>
                </div>
                <div class="stat-card">
                    <h3>漏洞率</h3>
                    <div class="value">{summary['vulnerability_rate']:.1f}%</div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
"""
    
    async def _generate_html_report(
        self,
        task_or_tasks: Any,
        results: List[POCVerificationResult],
        is_batch: bool = False,
        custom_template: Optional[CustomTemplate] = None,
        workflow_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        生成 HTML 格式报告
        
        Args:
            task_or_tasks: 单个任务或任务列表
            results: 验证结果列表
            is_batch: 是否为批量报告
            custom_template: 自定义模板
            workflow_data: 工作流数据
            
        Returns:
            str: HTML 报告内容
        """
        if is_batch:
            tasks = task_or_tasks
            task = None
        else:
            task = task_or_tasks
            tasks = [task]
        
        total_results = len(results)
        vulnerable_count = sum(1 for r in results if r.vulnerable)
        not_vulnerable_count = total_results - vulnerable_count
        severity_distribution = calculate_severity_distribution(results)
        
        template_vars = {}
        if custom_template:
            template_vars = {k: v.value for k, v in custom_template.variables.items()}
        
        toc_html = self._generate_table_of_contents() if self.is_section_enabled("table_of_contents") else ""
        charts_html = await self._generate_charts_html(results, severity_distribution)
        executive_summary_html = self._generate_executive_summary_html(
            total_results, vulnerable_count, severity_distribution
        )
        workflow_html = self._generate_workflow_section_html(workflow_data) if workflow_data else ""
        
        html_content = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.i18n.get('report_title')}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
    {self._get_modern_css()}
</head>
<body>
    <button class="theme-toggle" onclick="toggleTheme()" title="切换主题">
        <span class="icon-sun">☀️</span>
        <span class="icon-moon">🌙</span>
    </button>
    
    <div class="container">
        <nav class="toc-nav" id="tocNav">
            <div class="toc-header">
                <h3>{self.i18n.get('table_of_contents')}</h3>
                <button class="toc-close" onclick="toggleToc()">×</button>
            </div>
            {toc_html}
        </nav>
        
        <main class="main-content">
            <header class="header">
                <h1>{template_vars.get('title', self.i18n.get('report_title'))}</h1>
                <p>{self.i18n.get('generated_time')}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                {f'<p>POC: {task.poc_name}</p>' if task else ''}
            </header>
            
            {executive_summary_html if self.is_section_enabled('executive_summary') else ''}
            
            {charts_html}
            
            {workflow_html}
            
            <section id="verification-details" class="results">
                <h2>{self.i18n.get('verification_details')}</h2>
                {self._generate_results_html(results)}
            </section>
            
            {self._generate_recommendations_html(results) if self.is_section_enabled('recommendations') else ''}
            
            <footer class="footer">
                <p>{self.i18n.get('footer_text')}</p>
                <p class="timestamp">{datetime.now().isoformat()}</p>
            </footer>
        </main>
    </div>
    
    {self._get_javascript()}
</body>
</html>
"""
        
        if custom_template and custom_template.html_template:
            html_content = self._apply_custom_template(html_content, custom_template, template_vars)
        
        return html_content
    
    def _get_modern_css(self) -> str:
        """获取现代化 CSS 样式"""
        return """
    <style>
        :root {
            --primary-color: #3b82f6;
            --primary-dark: #2563eb;
            --danger-color: #ef4444;
            --warning-color: #f59e0b;
            --success-color: #10b981;
            --info-color: #6366f1;
            --bg-color: #f8fafc;
            --card-bg: #ffffff;
            --text-color: #1e293b;
            --text-muted: #64748b;
            --border-color: #e2e8f0;
            --shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
            --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
        }
        
        [data-theme="dark"] {
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --text-color: #f1f5f9;
            --text-muted: #94a3b8;
            --border-color: #334155;
            --shadow: 0 4px 6px -1px rgb(0 0 0 / 0.3), 0 2px 4px -2px rgb(0 0 0 / 0.3);
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
            transition: background-color 0.3s, color 0.3s;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            display: flex;
            gap: 20px;
        }
        
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 50%;
            width: 48px;
            height: 48px;
            cursor: pointer;
            box-shadow: var(--shadow);
            transition: all 0.3s;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.2rem;
        }
        
        .theme-toggle:hover {
            transform: scale(1.1);
            box-shadow: var(--shadow-lg);
        }
        
        [data-theme="dark"] .icon-sun { display: none; }
        [data-theme="light"] .icon-moon,
        :not([data-theme="dark"]) .icon-moon { display: none; }
        
        .toc-nav {
            position: fixed;
            left: 0;
            top: 0;
            width: 280px;
            height: 100vh;
            background: var(--card-bg);
            border-right: 1px solid var(--border-color);
            padding: 20px;
            overflow-y: auto;
            z-index: 100;
            transform: translateX(-100%);
            transition: transform 0.3s ease;
        }
        
        .toc-nav.open {
            transform: translateX(0);
        }
        
        .toc-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid var(--border-color);
        }
        
        .toc-header h3 {
            font-size: 1rem;
            color: var(--text-muted);
        }
        
        .toc-close {
            background: none;
            border: none;
            font-size: 1.5rem;
            cursor: pointer;
            color: var(--text-muted);
        }
        
        .toc-list {
            list-style: none;
        }
        
        .toc-list li {
            margin-bottom: 8px;
        }
        
        .toc-list a {
            color: var(--text-muted);
            text-decoration: none;
            font-size: 0.9rem;
            padding: 8px 12px;
            border-radius: 6px;
            display: block;
            transition: all 0.2s;
        }
        
        .toc-list a:hover {
            background: var(--primary-color);
            color: white;
        }
        
        .main-content {
            flex: 1;
            min-width: 0;
        }
        
        .header {
            text-align: center;
            margin-bottom: 40px;
            padding: 40px 20px;
            background: linear-gradient(135deg, var(--primary-color), var(--primary-dark));
            border-radius: 16px;
            color: white;
        }
        
        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
        }
        
        .header p {
            opacity: 0.9;
            font-size: 1rem;
        }
        
        .summary {
            background: var(--card-bg);
            padding: 30px;
            border-radius: 16px;
            margin-bottom: 30px;
            box-shadow: var(--shadow);
        }
        
        .summary h2 {
            color: var(--primary-color);
            margin-bottom: 20px;
            font-size: 1.5rem;
        }
        
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 20px;
        }
        
        .stat-card {
            background: var(--bg-color);
            padding: 24px;
            border-radius: 12px;
            text-align: center;
            transition: transform 0.2s, box-shadow 0.2s;
        }
        
        .stat-card:hover {
            transform: translateY(-4px);
            box-shadow: var(--shadow-lg);
        }
        
        .stat-card h3 {
            font-size: 0.85rem;
            color: var(--text-muted);
            margin-bottom: 8px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .stat-card .value {
            font-size: 2.5rem;
            font-weight: 700;
            color: var(--primary-color);
        }
        
        .stat-card .value.danger { color: var(--danger-color); }
        .stat-card .value.success { color: var(--success-color); }
        .stat-card .value.warning { color: var(--warning-color); }
        
        .charts-section {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .chart-card {
            background: var(--card-bg);
            padding: 24px;
            border-radius: 16px;
            box-shadow: var(--shadow);
        }
        
        .chart-card h3 {
            font-size: 1.1rem;
            margin-bottom: 16px;
            color: var(--text-color);
        }
        
        .chart-container {
            position: relative;
            height: 300px;
        }
        
        .results {
            background: var(--card-bg);
            padding: 30px;
            border-radius: 16px;
            margin-bottom: 30px;
            box-shadow: var(--shadow);
        }
        
        .results h2 {
            color: var(--primary-color);
            margin-bottom: 24px;
            padding-bottom: 12px;
            border-bottom: 2px solid var(--border-color);
        }
        
        .result-card {
            border: 1px solid var(--border-color);
            border-radius: 12px;
            margin-bottom: 16px;
            padding: 20px;
            transition: all 0.2s;
        }
        
        .result-card:hover {
            box-shadow: var(--shadow);
        }
        
        .result-card.vulnerable {
            border-left: 4px solid var(--danger-color);
            background: linear-gradient(90deg, rgba(239, 68, 68, 0.05), transparent);
        }
        
        .result-card.not-vulnerable {
            border-left: 4px solid var(--success-color);
        }
        
        .result-card h3 {
            margin-bottom: 12px;
            font-size: 1.1rem;
        }
        
        .result-meta {
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
            margin-bottom: 12px;
            font-size: 0.9rem;
            color: var(--text-muted);
        }
        
        .result-meta span {
            display: inline-flex;
            align-items: center;
            gap: 4px;
        }
        
        .severity {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
        }
        
        .severity-critical { background: #fef2f2; color: #dc2626; }
        .severity-high { background: #fff7ed; color: #ea580c; }
        .severity-medium { background: #fefce8; color: #ca8a04; }
        .severity-low { background: #f0fdf4; color: #16a34a; }
        .severity-info { background: #f1f5f9; color: #475569; }
        
        [data-theme="dark"] .severity-critical { background: #7f1d1d; color: #fca5a5; }
        [data-theme="dark"] .severity-high { background: #7c2d12; color: #fdba74; }
        [data-theme="dark"] .severity-medium { background: #713f12; color: #fde047; }
        [data-theme="dark"] .severity-low { background: #14532d; color: #86efac; }
        [data-theme="dark"] .severity-info { background: #334155; color: #cbd5e1; }
        
        .result-message {
            margin-top: 12px;
            padding: 12px;
            background: var(--bg-color);
            border-radius: 8px;
            font-size: 0.95rem;
        }
        
        .recommendations {
            background: var(--card-bg);
            padding: 30px;
            border-radius: 16px;
            margin-bottom: 30px;
            box-shadow: var(--shadow);
        }
        
        .recommendations h2 {
            color: var(--primary-color);
            margin-bottom: 20px;
        }
        
        .recommendation-item {
            padding: 16px;
            margin-bottom: 12px;
            background: var(--bg-color);
            border-radius: 8px;
            border-left: 4px solid var(--warning-color);
        }
        
        .recommendation-item h4 {
            margin-bottom: 8px;
            color: var(--text-color);
        }
        
        .recommendation-item p {
            color: var(--text-muted);
            font-size: 0.9rem;
        }
        
        .footer {
            text-align: center;
            padding: 30px;
            color: var(--text-muted);
            font-size: 0.9rem;
        }
        
        .footer .timestamp {
            font-size: 0.8rem;
            margin-top: 8px;
            opacity: 0.7;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 10px;
            }
            
            .header h1 {
                font-size: 1.8rem;
            }
            
            .stats {
                grid-template-columns: repeat(2, 1fr);
            }
            
            .charts-section {
                grid-template-columns: 1fr;
            }
            
            .result-meta {
                flex-direction: column;
                gap: 8px;
            }
        }
        
        @media print {
            .theme-toggle,
            .toc-nav {
                display: none !important;
            }
            
            body {
                background: white;
                color: black;
            }
            
            .container {
                max-width: 100%;
            }
            
            .header {
                background: none;
                color: black;
                border: 2px solid black;
            }
            
            .stat-card,
            .chart-card,
            .results,
            .recommendations {
                break-inside: avoid;
                box-shadow: none;
                border: 1px solid #ccc;
            }
            
            .result-card {
                break-inside: avoid;
            }
            
            a {
                color: black;
                text-decoration: none;
            }
        }
        
        .executive-summary-text {
            background: var(--bg-color);
            padding: 20px;
            border-radius: 12px;
            margin-top: 20px;
            line-height: 1.8;
            font-size: 1rem;
        }
        
        .heatmap-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
            gap: 8px;
        }
        
        .heatmap-cell {
            padding: 12px;
            border-radius: 8px;
            text-align: center;
            font-size: 0.8rem;
        }
        
        .heatmap-cell.risk-critical { background: #dc2626; color: white; }
        .heatmap-cell.risk-high { background: #ea580c; color: white; }
        .heatmap-cell.risk-medium { background: #ca8a04; color: white; }
        .heatmap-cell.risk-low { background: #16a34a; color: white; }
        .heatmap-cell.risk-none { background: #e2e8f0; color: #475569; }
        
        [data-theme="dark"] .heatmap-cell.risk-none { background: #334155; color: #cbd5e1; }
    </style>
"""
    
    def _generate_table_of_contents(self) -> str:
        """生成目录 HTML"""
        sections = [
            ("executive-summary", self.i18n.get('executive_summary')),
            ("severity-chart", self.i18n.get('severity_distribution')),
            ("timeline-chart", self.i18n.get('vulnerability_timeline')),
            ("heatmap", self.i18n.get('target_risk_heatmap')),
            ("verification-details", self.i18n.get('verification_details')),
            ("recommendations", self.i18n.get('recommendations')),
        ]
        
        items = []
        for section_id, title in sections:
            if self.is_section_enabled(section_id.replace('-chart', '').replace('-summary', '')):
                items.append(f'<li><a href="#{section_id}">{title}</a></li>')
        
        return f'<ul class="toc-list">{"".join(items)}</ul>'
    
    async def _generate_charts_html(
        self,
        results: List[POCVerificationResult],
        severity_distribution: Dict[str, int]
    ) -> str:
        """生成图表 HTML"""
        if not self.is_section_enabled('severity_distribution_chart') and \
           not self.is_section_enabled('vulnerability_timeline_chart') and \
           not self.is_section_enabled('target_risk_heatmap'):
            return ""
        
        severity_chart_html = ""
        if self.is_section_enabled('severity_distribution_chart'):
            severity_chart_html = self._generate_severity_chart_html(severity_distribution)
        
        timeline_chart_html = ""
        if self.is_section_enabled('vulnerability_timeline_chart'):
            timeline_chart_html = await self._generate_timeline_chart_html(results)
        
        heatmap_html = ""
        if self.is_section_enabled('target_risk_heatmap'):
            heatmap_html = self._generate_heatmap_html(results)
        
        return f"""
        <div class="charts-section">
            {severity_chart_html}
            {timeline_chart_html}
        </div>
        {heatmap_html}
"""
    
    def _generate_severity_chart_html(self, severity_distribution: Dict[str, int]) -> str:
        """生成严重度分布饼图 HTML"""
        labels = [self.i18n.get(sev) for sev in ['critical', 'high', 'medium', 'low', 'info']]
        data = [
            severity_distribution.get('critical', 0),
            severity_distribution.get('high', 0),
            severity_distribution.get('medium', 0),
            severity_distribution.get('low', 0),
            severity_distribution.get('info', 0)
        ]
        
        return f"""
        <div class="chart-card" id="severity-chart">
            <h3>{self.i18n.get('severity_distribution')}</h3>
            <div class="chart-container">
                <canvas id="severityPieChart"></canvas>
            </div>
        </div>
        <script>
            (function() {{
                const ctx = document.getElementById('severityPieChart').getContext('2d');
                new Chart(ctx, {{
                    type: 'doughnut',
                    data: {{
                        labels: {json.dumps(labels)},
                        datasets: [{{
                            data: {json.dumps(data)},
                            backgroundColor: ['#dc2626', '#ea580c', '#ca8a04', '#16a34a', '#64748b'],
                            borderWidth: 2,
                            borderColor: getComputedStyle(document.documentElement).getPropertyValue('--card-bg').trim()
                        }}]
                    }},
                    options: {{
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {{
                            legend: {{
                                position: 'bottom',
                                labels: {{
                                    padding: 20,
                                    usePointStyle: true
                                }}
                            }}
                        }}
                    }}
                }});
            }})();
        </script>
"""
    
    async def _generate_timeline_chart_html(self, results: List[POCVerificationResult]) -> str:
        """生成漏洞时间线图表 HTML"""
        timeline_data: Dict[str, int] = {}
        for result in results:
            if result.vulnerable:
                date_key = result.created_at.strftime('%Y-%m-%d')
                timeline_data[date_key] = timeline_data.get(date_key, 0) + 1
        
        sorted_dates = sorted(timeline_data.keys())
        labels = sorted_dates[-10:] if len(sorted_dates) > 10 else sorted_dates
        data = [timeline_data.get(date, 0) for date in labels]
        
        return f"""
        <div class="chart-card" id="timeline-chart">
            <h3>{self.i18n.get('vulnerability_timeline')}</h3>
            <div class="chart-container">
                <canvas id="timelineChart"></canvas>
            </div>
        </div>
        <script>
            (function() {{
                const ctx = document.getElementById('timelineChart').getContext('2d');
                new Chart(ctx, {{
                    type: 'line',
                    data: {{
                        labels: {json.dumps(labels)},
                        datasets: [{{
                            label: 'Vulnerabilities',
                            data: {json.dumps(data)},
                            borderColor: '#3b82f6',
                            backgroundColor: 'rgba(59, 130, 246, 0.1)',
                            fill: true,
                            tension: 0.4
                        }}]
                    }},
                    options: {{
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {{
                            legend: {{
                                display: false
                            }}
                        }},
                        scales: {{
                            y: {{
                                beginAtZero: true,
                                ticks: {{
                                    stepSize: 1
                                }}
                            }}
                        }}
                    }}
                }});
            }})();
        </script>
"""
    
    def _generate_heatmap_html(self, results: List[POCVerificationResult]) -> str:
        """生成目标风险热力图 HTML"""
        target_risks: Dict[str, str] = {}
        severity_order = {'critical': 4, 'high': 3, 'medium': 2, 'low': 1, 'info': 0}
        
        for result in results:
            if result.vulnerable:
                target = result.target
                current_severity = result.severity or 'info'
                if target not in target_risks or \
                   severity_order.get(current_severity, 0) > severity_order.get(target_risks[target], 0):
                    target_risks[target] = current_severity
        
        cells = []
        for target, risk in sorted(target_risks.items(), key=lambda x: severity_order.get(x[1], 0), reverse=True)[:20]:
            cells.append(f'''
            <div class="heatmap-cell risk-{risk}">
                <div class="target-name">{target[:30]}{'...' if len(target) > 30 else ''}</div>
                <div class="risk-level">{self.i18n.get(risk)}</div>
            </div>''')
        
        if not cells:
            cells.append(f'<div class="heatmap-cell risk-none">{self.i18n.get("no_vulnerabilities_found")}</div>')
        
        return f"""
        <div class="chart-card" id="heatmap">
            <h3>{self.i18n.get('target_risk_heatmap')}</h3>
            <div class="heatmap-container">
                {''.join(cells)}
            </div>
        </div>
"""
    
    def _generate_executive_summary_html(
        self,
        total_results: int,
        vulnerable_count: int,
        severity_distribution: Dict[str, int]
    ) -> str:
        """生成执行摘要 HTML"""
        not_vulnerable_count = total_results - vulnerable_count
        vulnerability_rate = (vulnerable_count / total_results * 100) if total_results > 0 else 0
        
        summary_text = self.i18n.get(
            'executive_summary_text',
            total=total_results,
            vuln=vulnerable_count,
            rate=f"{vulnerability_rate:.1f}",
            critical=severity_distribution.get('critical', 0),
            high=severity_distribution.get('high', 0),
            medium=severity_distribution.get('medium', 0),
            low=severity_distribution.get('low', 0)
        )
        
        return f"""
        <section id="executive-summary" class="summary">
            <h2>{self.i18n.get('executive_summary')}</h2>
            <div class="stats">
                <div class="stat-card">
                    <h3>{self.i18n.get('total_results')}</h3>
                    <div class="value">{total_results}</div>
                </div>
                <div class="stat-card">
                    <h3>{self.i18n.get('vulnerabilities_found')}</h3>
                    <div class="value danger">{vulnerable_count}</div>
                </div>
                <div class="stat-card">
                    <h3>{self.i18n.get('no_vulnerabilities')}</h3>
                    <div class="value success">{not_vulnerable_count}</div>
                </div>
                <div class="stat-card">
                    <h3>{self.i18n.get('vulnerability_rate')}</h3>
                    <div class="value warning">{vulnerability_rate:.1f}%</div>
                </div>
            </div>
            <div class="executive-summary-text">
                {summary_text}
            </div>
        </section>
"""
    
    def _generate_results_html(self, results: List[POCVerificationResult]) -> str:
        """生成结果 HTML 片段"""
        html_parts = []
        
        for result in results:
            vulnerable_class = "vulnerable" if result.vulnerable else "not-vulnerable"
            severity_class = f"severity-{result.severity or 'info'}"
            severity_text = self.i18n.get(result.severity or 'info')
            
            html_parts.append(f"""
            <div class="result-card {vulnerable_class}">
                <h3>{result.poc_name}</h3>
                <div class="result-meta">
                    <span class="severity {severity_class}">{severity_text}</span>
                    <span>🎯 {self.i18n.get('target')}: {result.target}</span>
                    <span>📊 {self.i18n.get('confidence')}: {result.confidence:.2f}</span>
                    <span>📈 {self.i18n.get('cvss_score')}: {result.cvss_score or 0:.1f}</span>
                </div>
                <div class="result-message">
                    <strong>{self.i18n.get('result')}:</strong> {result.message}
                </div>
            </div>
""")
        
        if not html_parts:
            return f'<p class="no-results">{self.i18n.get("no_vulnerabilities_found")}</p>'
        
        return "\n".join(html_parts)
    
    def _generate_recommendations_html(self, results: List[POCVerificationResult]) -> str:
        """生成修复建议 HTML"""
        vulnerable_results = [r for r in results if r.vulnerable]
        
        if not vulnerable_results:
            return ""
        
        recommendations = []
        severity_groups: Dict[str, List[POCVerificationResult]] = {}
        
        for result in vulnerable_results:
            sev = result.severity or 'info'
            if sev not in severity_groups:
                severity_groups[sev] = []
            severity_groups[sev].append(result)
        
        if severity_groups.get('critical'):
            recommendations.append({
                'title': self.i18n.get('critical') + ' ' + self.i18n.get('vulnerabilities_detected'),
                'content': f"发现 {len(severity_groups['critical'])} 个严重漏洞，需要立即修复。这些漏洞可能导致系统被完全控制。"
            })
        
        if severity_groups.get('high'):
            recommendations.append({
                'title': self.i18n.get('high') + ' ' + self.i18n.get('vulnerabilities_detected'),
                'content': f"发现 {len(severity_groups['high'])} 个高危漏洞，建议在短期内修复。"
            })
        
        recommendations.append({
            'title': '通用建议',
            'content': '1. 及时更新所有软件和依赖包到最新版本\n2. 实施最小权限原则\n3. 定期进行安全审计和渗透测试\n4. 建立漏洞响应流程'
        })
        
        items = []
        for rec in recommendations:
            items.append(f"""
            <div class="recommendation-item">
                <h4>{rec['title']}</h4>
                <p>{rec['content']}</p>
            </div>
""")
        
        return f"""
        <section id="recommendations" class="recommendations">
            <h2>{self.i18n.get('recommendations')}</h2>
            {''.join(items)}
        </section>
"""
    
    def _generate_workflow_section_html(self, workflow_data: Dict[str, Any]) -> str:
        """生成工作流数据展示 HTML"""
        if not workflow_data:
            return ""
        
        execution_history = workflow_data.get("execution_history", [])
        task_plans = workflow_data.get("task_plans", [])
        progress = workflow_data.get("progress", 0)
        status = workflow_data.get("status", "pending")
        
        completed_count = sum(1 for r in execution_history if r.get("status") in ["success", "completed"])
        failed_count = sum(1 for r in execution_history if r.get("status") == "failed")
        total_duration = sum(r.get("execution_time", 0) or 0 for r in execution_history)
        
        overview_html = f"""
        <div class="workflow-overview" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-bottom: 25px;">
            <div class="workflow-stat" style="background: var(--bg-color); padding: 15px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: var(--primary-color);">{len(execution_history)}</div>
                <div style="font-size: 12px; color: var(--text-muted);">总步骤数</div>
            </div>
            <div class="workflow-stat" style="background: var(--bg-color); padding: 15px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: var(--success-color);">{completed_count}</div>
                <div style="font-size: 12px; color: var(--text-muted);">已完成</div>
            </div>
            <div class="workflow-stat" style="background: var(--bg-color); padding: 15px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: var(--danger-color);">{failed_count}</div>
                <div style="font-size: 12px; color: var(--text-muted);">失败</div>
            </div>
            <div class="workflow-stat" style="background: var(--bg-color); padding: 15px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: var(--primary-color);">{total_duration:.2f}s</div>
                <div style="font-size: 12px; color: var(--text-muted);">执行时长</div>
            </div>
        </div>
        """
        
        timeline_html = ""
        if execution_history:
            for idx, record in enumerate(execution_history):
                record_status = record.get("status", "pending")
                status_class = record_status if record_status in ["success", "failed", "running", "pending"] else "pending"
                duration_text = f"{record.get('execution_time', 0):.2f}s" if record.get("execution_time") else "-"
                error_msg = record.get("error", "")
                
                timeline_html += f"""
                <div class="timeline-item {status_class}" style="display: flex; gap: 15px; margin-bottom: 15px; padding: 15px; background: var(--bg-color); border-radius: 8px; border-left: 3px solid var(--primary-color);">
                    <div style="min-width: 30px; height: 30px; background: var(--primary-color); color: white; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 14px;">{idx + 1}</div>
                    <div style="flex: 1;">
                        <div style="font-weight: 600; margin-bottom: 5px;">{record.get('node_name', record.get('task', f'步骤 {idx + 1}'))}</div>
                        <div style="font-size: 12px; color: var(--text-muted);">
                            <span>类型: {record.get('node_type', 'N/A')}</span>
                            <span style="margin-left: 15px;">状态: {record_status}</span>
                            <span style="margin-left: 15px;">工具: {record.get('tool_name', 'N/A')}</span>
                        </div>
                        {f'<div style="font-size: 12px; color: var(--success-color); font-weight: 500; margin-top: 5px;">耗时: {duration_text}</div>' if record.get('execution_time') else ''}
                        {f'<div style="color: var(--danger-color); margin-top: 5px; font-size: 12px;">错误: {error_msg}</div>' if error_msg else ''}
                    </div>
                </div>
                """
        else:
            timeline_html = '<p style="color: var(--text-muted); text-align: center; padding: 20px;">暂无执行记录</p>'
        
        plans_html = ""
        if task_plans:
            for plan in sorted(task_plans, key=lambda x: x.get("priority", 5), reverse=True):
                plan_status = plan.get("status", "pending")
                status_class = plan_status if plan_status in ["completed", "running", "pending", "failed"] else "pending"
                
                plans_html += f"""
                <div class="plan-item" style="display: flex; align-items: center; gap: 15px; padding: 12px 15px; background: var(--bg-color); border-radius: 8px; margin-bottom: 10px;">
                    <div style="min-width: 30px; height: 30px; background: var(--primary-color); color: white; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 12px;">{plan.get('priority', 5)}</div>
                    <div style="flex: 1;">
                        <div style="font-weight: 600;">{plan.get('plan_name', 'N/A')}</div>
                        <div style="font-size: 12px; color: var(--text-muted);">
                            类型: {plan.get('plan_type', 'N/A')} | ID: {plan.get('plan_id', 'N/A')}
                        </div>
                    </div>
                    <span style="padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 500; background: var(--bg-color);">{plan_status}</span>
                </div>
                """
        else:
            plans_html = '<p style="color: var(--text-muted); text-align: center; padding: 20px;">暂无任务规划</p>'
        
        progress_html = ""
        if progress > 0:
            progress_html = f"""
            <div style="margin-top: 15px;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                    <span style="font-size: 12px; color: var(--text-muted);">执行进度</span>
                    <span style="font-size: 12px; font-weight: 500;">{progress}%</span>
                </div>
                <div style="width: 100%; height: 8px; background: var(--border-color); border-radius: 4px; overflow: hidden;">
                    <div style="height: 100%; width: {progress}%; background: linear-gradient(90deg, var(--success-color), #34d399);"></div>
                </div>
            </div>
            """
        
        return f"""
        <section id="workflow-details" class="results" style="background: var(--card-bg); padding: 30px; border-radius: 16px; margin-bottom: 30px; box-shadow: var(--shadow);">
            <h2 style="color: var(--primary-color); margin-bottom: 24px; padding-bottom: 12px; border-bottom: 2px solid var(--border-color);">⚡ 工作流执行详情</h2>
            
            {overview_html}
            
            {progress_html}
            
            <div style="margin-top: 25px;">
                <h3 style="margin-bottom: 15px; color: var(--text-color);">📋 执行历史</h3>
                {timeline_html}
            </div>
            
            <div style="margin-top: 25px;">
                <h3 style="margin-bottom: 15px; color: var(--text-color);">📝 任务规划</h3>
                {plans_html}
            </div>
        </section>
        """
    
    def _get_javascript(self) -> str:
        """获取 JavaScript 代码"""
        return """
    <script>
        function toggleTheme() {
            const body = document.body;
            const currentTheme = body.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
            body.setAttribute('data-theme', newTheme);
            localStorage.setItem('theme', newTheme);
        }
        
        function toggleToc() {
            const toc = document.getElementById('tocNav');
            toc.classList.toggle('open');
        }
        
        (function() {
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.body.setAttribute('data-theme', savedTheme);
        })();
        
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function(e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            });
        });
    </script>
"""
    
    def _apply_custom_template(
        self,
        html_content: str,
        template: CustomTemplate,
        variables: Dict[str, Any]
    ) -> str:
        """应用自定义模板"""
        result = html_content
        
        for var_name, var_value in variables.items():
            placeholder = f'{{{{{var_name}}}}}'
            result = result.replace(placeholder, str(var_value))
        
        for section_id, section in template.sections.items():
            if not section.enabled:
                start_marker = f'<!-- SECTION:{section_id} -->'
                end_marker = f'<!-- END_SECTION:{section_id} -->'
                if start_marker in result and end_marker in result:
                    start = result.find(start_marker)
                    end = result.find(end_marker) + len(end_marker)
                    result = result[:start] + result[end:]
        
        return result
    
    async def _generate_json_report(
        self,
        task_or_tasks: Any,
        results: List[POCVerificationResult],
        is_batch: bool = False,
        custom_template: Optional[CustomTemplate] = None,
        workflow_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        生成 JSON 格式报告
        
        Args:
            task_or_tasks: 单个任务或任务列表
            results: 验证结果列表
            is_batch: 是否为批量报告
            custom_template: 自定义模板
            workflow_data: 工作流数据
            
        Returns:
            str: JSON 报告内容
        """
        total_results = len(results)
        vulnerable_count = sum(1 for r in results if r.vulnerable)
        severity_distribution = calculate_severity_distribution(results)
        
        report_data = {
            "report_type": "batch" if is_batch else "single",
            "generated_at": datetime.now().isoformat(),
            "language": self.i18n.language.value,
            "summary": {
                "total_results": total_results,
                "vulnerable_count": vulnerable_count,
                "not_vulnerable_count": total_results - vulnerable_count,
                "vulnerability_rate": (vulnerable_count / total_results * 100) if total_results > 0 else 0,
                "severity_distribution": severity_distribution
            },
            "results": [
                {
                    "id": str(result.id),
                    "poc_name": result.poc_name,
                    "poc_id": result.poc_id,
                    "target": result.target,
                    "vulnerable": result.vulnerable,
                    "message": result.message,
                    "output": result.output,
                    "error": result.error,
                    "execution_time": result.execution_time,
                    "confidence": result.confidence,
                    "severity": result.severity,
                    "cvss_score": result.cvss_score,
                    "created_at": result.created_at.isoformat()
                }
                for result in results
            ]
        }
        
        if custom_template:
            report_data["template_name"] = custom_template.name
            report_data["template_variables"] = {k: v.value for k, v in custom_template.variables.items()}
        
        if workflow_data:
            report_data["workflow"] = workflow_data
        
        return json.dumps(report_data, ensure_ascii=False, indent=2)
    
    async def _generate_pdf_report(
        self,
        task_or_tasks: Any,
        results: List[POCVerificationResult],
        is_batch: bool = False,
        custom_template: Optional[CustomTemplate] = None,
        workflow_data: Optional[Dict[str, Any]] = None
    ) -> Union[str, bytes]:
        """
        生成 PDF 格式报告
        
        Args:
            task_or_tasks: 单个任务或任务列表
            results: 验证结果列表
            is_batch: 是否为批量报告
            custom_template: 自定义模板
            workflow_data: 工作流数据
            
        Returns:
            Union[str, bytes]: PDF 报告内容或 HTML 内容
        """
        html_content = await self._generate_html_report(
            task_or_tasks,
            results,
            is_batch,
            custom_template,
            workflow_data
        )
        
        try:
            from weasyprint import HTML
            pdf_bytes = HTML(string=html_content).write_pdf()
            return pdf_bytes
        except ImportError:
            logger.warning("⚠️ weasyprint 未安装,返回 HTML 格式")
            return html_content
        except Exception as e:
            logger.error(f"❌ 生成 PDF 失败: {str(e)}")
            return html_content
    
    async def generate_execution_summary(
        self,
        verification_task: POCVerificationTask
    ) -> Dict[str, Any]:
        """
        生成执行摘要
        
        Args:
            verification_task: POC 验证任务对象
            
        Returns:
            Dict: 执行摘要字典
        """
        results = await POCVerificationResult.filter(
            verification_task=verification_task.id
        ).order_by("-created_at")
        
        total_results = len(results)
        vulnerable_count = sum(1 for r in results if r.vulnerable)
        total_execution_time = sum(r.execution_time for r in results)
        average_execution_time = total_execution_time / total_results if total_results > 0 else 0
        severity_distribution = calculate_severity_distribution(results)
        targets = list(set(r.target for r in results))
        
        return {
            "task_id": str(verification_task.id),
            "poc_name": verification_task.poc_name,
            "poc_id": verification_task.poc_id,
            "target": verification_task.target,
            "status": verification_task.status,
            "progress": verification_task.progress,
            "created_at": verification_task.created_at.isoformat(),
            "updated_at": verification_task.updated_at.isoformat(),
            "summary": {
                "total_results": total_results,
                "vulnerable_count": vulnerable_count,
                "not_vulnerable_count": total_results - vulnerable_count,
                "vulnerability_rate": (vulnerable_count / total_results * 100) if total_results > 0 else 0,
                "total_execution_time": total_execution_time,
                "average_execution_time": average_execution_time,
                "severity_distribution": severity_distribution
            },
            "targets": targets,
            "result_count": total_results
        }
    
    async def generate_vulnerability_details(
        self,
        results: List[POCVerificationResult]
    ) -> List[Dict[str, Any]]:
        """
        生成漏洞详情列表
        
        Args:
            results: 验证结果列表
            
        Returns:
            List[Dict]: 漏洞详情列表
        """
        details = []
        
        for result in results:
            if result.vulnerable:
                details.append({
                    "poc_name": result.poc_name,
                    "poc_id": result.poc_id,
                    "target": result.target,
                    "severity": result.severity,
                    "cvss_score": result.cvss_score,
                    "confidence": result.confidence,
                    "message": result.message,
                    "output": result.output,
                    "execution_time": result.execution_time,
                    "created_at": result.created_at.isoformat()
                })
        
        return details
    
    async def generate_statistics(
        self,
        results: List[POCVerificationResult]
    ) -> Dict[str, Any]:
        """
        生成统计信息
        
        Args:
            results: 验证结果列表
            
        Returns:
            Dict: 统计信息字典
        """
        if not results:
            return {
                "total": 0,
                "vulnerable": 0,
                "not_vulnerable": 0,
                "vulnerability_rate": 0,
                "average_confidence": 0,
                "average_cvss_score": 0,
                "severity_distribution": {}
            }
        
        total = len(results)
        vulnerable_count = sum(1 for r in results if r.vulnerable)
        severity_distribution = calculate_severity_distribution(results)
        average_confidence = sum(r.confidence for r in results) / total
        average_cvss_score = sum(r.cvss_score or 0 for r in results) / total
        
        return {
            "total": total,
            "vulnerable": vulnerable_count,
            "not_vulnerable": total - vulnerable_count,
            "vulnerability_rate": (vulnerable_count / total * 100) if total > 0 else 0,
            "average_confidence": average_confidence,
            "average_cvss_score": average_cvss_score,
            "severity_distribution": severity_distribution
        }
    
    async def generate_executive_summary_report(
        self,
        verification_task: POCVerificationTask,
        output_path: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        生成执行摘要报告
        
        Args:
            verification_task: POC 验证任务对象
            output_path: 输出文件路径
            
        Returns:
            Dict: 执行摘要报告
        """
        results = await POCVerificationResult.filter(
            verification_task=verification_task.id
        ).order_by("-created_at")
        
        total_results = len(results)
        vulnerable_results = [r for r in results if r.vulnerable]
        vulnerable_count = len(vulnerable_results)
        severity_distribution = calculate_severity_distribution(results)
        
        affected_targets = list(set(r.target for r in vulnerable_results))
        
        risk_level = "低"
        if severity_distribution.get('critical', 0) > 0:
            risk_level = "严重"
        elif severity_distribution.get('high', 0) > 0:
            risk_level = "高"
        elif severity_distribution.get('medium', 0) > 0:
            risk_level = "中"
        
        summary_text = self.i18n.get(
            'executive_summary_text',
            total=total_results,
            vuln=vulnerable_count,
            rate=f"{(vulnerable_count / total_results * 100) if total_results > 0 else 0:.1f}",
            critical=severity_distribution.get('critical', 0),
            high=severity_distribution.get('high', 0),
            medium=severity_distribution.get('medium', 0),
            low=severity_distribution.get('low', 0)
        )
        
        report = {
            "report_type": "executive_summary",
            "generated_at": datetime.now().isoformat(),
            "task_info": {
                "task_id": str(verification_task.id),
                "poc_name": verification_task.poc_name,
                "target": verification_task.target
            },
            "overview": {
                "total_scanned": total_results,
                "vulnerabilities_found": vulnerable_count,
                "vulnerability_rate": (vulnerable_count / total_results * 100) if total_results > 0 else 0,
                "risk_level": risk_level
            },
            "severity_breakdown": severity_distribution,
            "affected_targets": affected_targets,
            "summary_text": summary_text,
            "recommendations": self._generate_recommendations_list(vulnerable_results)
        }
        
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(report, f, ensure_ascii=False, indent=2)
            logger.info(f"✅ 执行摘要报告已保存: {output_path}")
        
        return report
    
    def _generate_recommendations_list(self, vulnerable_results: List[POCVerificationResult]) -> List[Dict[str, str]]:
        """生成建议列表"""
        recommendations = []
        
        severity_groups: Dict[str, List[POCVerificationResult]] = {}
        for result in vulnerable_results:
            sev = result.severity or 'info'
            if sev not in severity_groups:
                severity_groups[sev] = []
            severity_groups[sev].append(result)
        
        if severity_groups.get('critical'):
            recommendations.append({
                "priority": "critical",
                "title": "立即修复严重漏洞",
                "description": f"发现 {len(severity_groups['critical'])} 个严重漏洞，可能导致系统被完全控制",
                "action": "立即应用安全补丁，限制受影响系统的访问"
            })
        
        if severity_groups.get('high'):
            recommendations.append({
                "priority": "high",
                "title": "短期内修复高危漏洞",
                "description": f"发现 {len(severity_groups['high'])} 个高危漏洞",
                "action": "在 7 天内完成修复"
            })
        
        if severity_groups.get('medium'):
            recommendations.append({
                "priority": "medium",
                "title": "计划修复中危漏洞",
                "description": f"发现 {len(severity_groups['medium'])} 个中危漏洞",
                "action": "在 30 天内完成修复"
            })
        
        recommendations.append({
            "priority": "general",
            "title": "通用安全建议",
            "description": "持续改进安全态势",
            "action": "定期安全审计、漏洞扫描、安全培训"
        })
        
        return recommendations


report_generator = ReportGenerator()
